//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplifiedPaint.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimplifiedPaint.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program has been written as a student project. More info on github - link above..
        /// </summary>
        internal static string AppAbout {
            get {
                return ResourceManager.GetString("AppAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string AppCancel {
            get {
                return ResourceManager.GetString("AppCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        internal static string AppDiscard {
            get {
                return ResourceManager.GetString("AppDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard all changes (Ctrl + D).
        /// </summary>
        internal static string AppDiscardDescription {
            get {
                return ResourceManager.GetString("AppDiscardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to discard all changes? It&apos;ll be not possible to restore them again..
        /// </summary>
        internal static string AppDiscardMessage {
            get {
                return ResourceManager.GetString("AppDiscardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes?.
        /// </summary>
        internal static string AppDiscardMessageTitle {
            get {
                return ResourceManager.GetString("AppDiscardMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can undo up to {0} moves.
        /// </summary>
        internal static string AppHistorySize {
            get {
                return ResourceManager.GetString("AppHistorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string AppNone {
            get {
                return ResourceManager.GetString("AppNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string AppOk {
            get {
                return ResourceManager.GetString("AppOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        internal static string AppOpen {
            get {
                return ResourceManager.GetString("AppOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open image (Ctrl + O).
        /// </summary>
        internal static string AppOpenDescription {
            get {
                return ResourceManager.GetString("AppOpenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo (Ctrl + Y).
        /// </summary>
        internal static string AppRedo {
            get {
                return ResourceManager.GetString("AppRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize image (Ctrl + R).
        /// </summary>
        internal static string AppResize {
            get {
                return ResourceManager.GetString("AppResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change canvas size.
        /// </summary>
        internal static string AppResizeDescription {
            get {
                return ResourceManager.GetString("AppResizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string AppResizeHeight {
            get {
                return ResourceManager.GetString("AppResizeHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string AppResizeLock {
            get {
                return ResourceManager.GetString("AppResizeLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock the proportions between width and height.
        /// </summary>
        internal static string AppResizeLockDescription {
            get {
                return ResourceManager.GetString("AppResizeLockDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string AppResizeWidth {
            get {
                return ResourceManager.GetString("AppResizeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string AppSave {
            get {
                return ResourceManager.GetString("AppSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save image as PNG file (Ctrl + S).
        /// </summary>
        internal static string AppSaveDescription {
            get {
                return ResourceManager.GetString("AppSaveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with the given name already exists. Do you want to overwrite it?.
        /// </summary>
        internal static string AppSaveFileOverwrite {
            get {
                return ResourceManager.GetString("AppSaveFileOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes. Do you want to save before exit?.
        /// </summary>
        internal static string AppSaveFileQuestion {
            get {
                return ResourceManager.GetString("AppSaveFileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string AppSaveFileTitle {
            get {
                return ResourceManager.GetString("AppSaveFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simpliefied Paint.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo (Ctrl + Z).
        /// </summary>
        internal static string AppUndo {
            get {
                return ResourceManager.GetString("AppUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes foreground or background color of the current tool.
        /// </summary>
        internal static string CanvasColorPickerDescription {
            get {
                return ResourceManager.GetString("CanvasColorPickerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current tool: {0}.
        /// </summary>
        internal static string CanvasCurrnetTool {
            get {
                return ResourceManager.GetString("CanvasCurrnetTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New image.
        /// </summary>
        internal static string CanvasIsNew {
            get {
                return ResourceManager.GetString("CanvasIsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string CanvasIsSaved {
            get {
                return ResourceManager.GetString("CanvasIsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved.
        /// </summary>
        internal static string CanvasIsUnsaved {
            get {
                return ResourceManager.GetString("CanvasIsUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to chagne height.
        /// </summary>
        internal static string CanvasResizeHorizontal {
            get {
                return ResourceManager.GetString("CanvasResizeHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to chagne width.
        /// </summary>
        internal static string CanvasResizeVertical {
            get {
                return ResourceManager.GetString("CanvasResizeVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas size: {0}x{1}.
        /// </summary>
        internal static string CanvasSize {
            get {
                return ResourceManager.GetString("CanvasSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes thickness of the current tool.
        /// </summary>
        internal static string CanvasThicknessDescription {
            get {
                return ResourceManager.GetString("CanvasThicknessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to github.
        /// </summary>
        internal static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint.
        /// </summary>
        internal static string MainPageName {
            get {
                return ResourceManager.GetString("MainPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string PluginsAuthor {
            get {
                return ResourceManager.GetString("PluginsAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string PluginsDescription {
            get {
                return ResourceManager.GetString("PluginsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string PluginsEnabled {
            get {
                return ResourceManager.GetString("PluginsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string PluginsFile {
            get {
                return ResourceManager.GetString("PluginsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string PluginsIcon {
            get {
                return ResourceManager.GetString("PluginsIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PluginsName {
            get {
                return ResourceManager.GetString("PluginsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string PluginsVersion {
            get {
                return ResourceManager.GetString("PluginsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string SettingsPageAbout {
            get {
                return ResourceManager.GetString("SettingsPageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string SettingsPageAppearance {
            get {
                return ResourceManager.GetString("SettingsPageAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        internal static string SettingsPageColor {
            get {
                return ResourceManager.GetString("SettingsPageColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size:.
        /// </summary>
        internal static string SettingsPageFontSize {
            get {
                return ResourceManager.GetString("SettingsPageFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        internal static string SettingsPageInterface {
            get {
                return ResourceManager.GetString("SettingsPageInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string SettingsPageLanguage {
            get {
                return ResourceManager.GetString("SettingsPageLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPageName {
            get {
                return ResourceManager.GetString("SettingsPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string SettingsPagePlugins {
            get {
                return ResourceManager.GetString("SettingsPagePlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        internal static string SettingsPageTheme {
            get {
                return ResourceManager.GetString("SettingsPageTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string ToolsOptionsAdvanced {
            get {
                return ResourceManager.GetString("ToolsOptionsAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backcolor.
        /// </summary>
        internal static string ToolsOptionsBackColor {
            get {
                return ResourceManager.GetString("ToolsOptionsBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecolor.
        /// </summary>
        internal static string ToolsOptionsForeColor {
            get {
                return ResourceManager.GetString("ToolsOptionsForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string ToolsOptionsStandard {
            get {
                return ResourceManager.GetString("ToolsOptionsStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        internal static string ToolsOptionsThickness {
            get {
                return ResourceManager.GetString("ToolsOptionsThickness", resourceCulture);
            }
        }
    }
}
